### ISSUE TITLE
Nacho López - Página en blanco HTML5

### ISSUE THREAD

**Issue by milq** [milq/lmsgi#1]
Tengo un problema con HTML5, no me carga bien:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>XHTML 5.1 blank page</title>
  </head>

  <bodyb>

  </body>
</html>
```

¿Qué hago mal?

**Comment by JKonde1990** [comment]
Yo te ayudo amijo

**Comment by JavierOrtegaFernandez** [comment]
Sustituye <bodyb> por <body>

**Comment by antsan98** [comment]
En la línea 8 <bodyb> es <body>

**Comment by Sacave96** [comment]
Te recomiendo consultar http://www.w3schools.com/

**Comment by juanjo93** [comment]
en el body la B del final quitala campeon ;)

**Comment by requixworld** [comment]
illo eso está to mal, suspendio

**Comment by juanjo93** [comment]
Hola yo solo pasaba por aqui

**Comment by JKonde1990** [comment]
Espacio patrocinado por sonicolor

**Comment by dani96alcala** [comment]
pa k kieres saber eso jaja salu2

**Comment by requixworld** [comment]
eres como el CSS de mi corazón <3

**Comment by requixworld** [comment]
He vuelto

**Comment by juanjo93** [comment]
quien juega luego al lol?

**Comment by JKonde1990** [comment]
Fran challenger

**Comment by requixworld** [comment]
Fran Jayce Main new meta

**Comment by dani96alcala** [comment]
el new meta está op

**Comment by JKonde1990** [comment]
moscosoooooooooooooooooooo

**Comment by dani96alcala** [comment]
:(

**Comment by juanjo93** [comment]
soraka ap jungla broken

**Comment by Sacave96** [comment]
Este es el mas malo del juego http://euw.op.gg/summoner/userName=baltraxx

**Comment by requixworld** [comment]
Main Malzahar http://www.leagueofgraphs.com/summoner/euw/RequixWorld

**Comment by dani96alcala** [comment]
Malzahar op, te echa la Q y la ulti y GG

**Comment by juanjo93** [comment]
mirad el nuevo amazing! http://euw.op.gg/summoner/userName=davidbetico1996

**Comment by dani96alcala** [comment]
En realidad soy lvl 12 bronza, no tengo ni flowers del juego... :(

**Comment by requixworld** [comment]
no yorickees.

**Comment by Sacave96** [comment]
http://euw.op.gg/summoner/userName=Stomb respect

**Comment by dani96alcala** [comment]
algun oro pa que me rushee rankeds plss :(( ?

**Comment by requixworld** [comment]
http://euw.op.gg/summoner/username=requixworld Hacerme carrito que quiero subir a Oro

**Comment by juanjo93** [comment]
http://euw.op.gg/summoner/userName=lagiacrus1808
Aqui el primo de faker

**Comment by dani96alcala** [comment]
carrito op gg and surr at 20´

**Comment by requixworld** [comment]
Solo sé usar a Malzahar, aviso.

**Comment by requixworld** [comment]
Que no es mentira loco http://euw.op.gg/summoner/userName=RequixWorld

**Comment by juanjo93** [comment]
El campeon http://euw.op.gg/summoner/userName=TripleH10

**Comment by juanjo93** [comment]
El campeon http://euw.op.gg/summoner/userName=TripleH10

**Comment by Sacave96** [comment]
Add me guys http://euw.op.gg/summoner/userName=Robusdack Soy el salva

**Comment by javier18081969** [comment]
nacho como  eres en el lol?

**Comment by dani96alcala** [comment]
http://euw.op.gg/summoner/userName=DansLambda OOOOOOOOPPPP

**Comment by requixworld** [comment]
lo mismo el polvorones tambien jugaba al lol y se fue

**Comment by dani96alcala** [comment]
xdddd
